experiment:
  name: cifar10_byz_vr_dm21_krum_withoutatt
  seed: 42
  log_level: INFO
  save_path: "./results/test/byz_vr_dm21_krum_withoutatt"
resources:
  gpus:
  - 0
dataset:
  batch_size: 16
  train:
    class_path: fl_framework.data.datasets.CIFAR10Dataset
    params:
      data_dir: data_cache
      train: true
  test:
    class_path: fl_framework.data.datasets.CIFAR10Dataset
    params:
      data_dir: data_cache
      train: false
  partition:
    iid: true
    seed: 42

model:
  class_path: fl_framework.components.models.resnet_18_for_10.ResNet18For10
  params:
    in_channels: 3

training:
  rounds: 100
  round_steps: 300
  train_loss_function:
    class_path: torch.nn.CrossEntropyLoss
  test_loss_function:
    class_path: torch.nn.CrossEntropyLoss
  metrics:
  - class_path: fl_framework.utils.metrics.TopKAccuracy
    params:
      k: 1
optimizer:
  class_path: fl_framework.components.optimizers.byz_dm21.ByzDM21
  params:
    lr: 0.01
    momentum: 0.9
    compression_ratio: 0.1
    use_vr: true
aggregator:
  class_path: fl_framework.components.aggregators.krum.KrumAggregator
  params:
    num_byzantine: 4
honest:
  num_clients: 16
byzantine:
  num_clients: 0
  attack:
    class_path: fl_framework.components.attacks.zero_gradient.ZeroGradientAttack
    params: {}
