experiment:
  name: mnist_katyusha_geometric_withoutatt
  seed: 42
  log_level: INFO
  save_path: "./results_CIFAR10_920_former/sgd_compress_withoutatt"
resources:
  gpus:
  - 1
dataset:
  batch_size: 16
  train:
    class_path: fl_framework.data.datasets.CIFAR10Dataset
    params:
      data_dir: data_cache        # ← directory only
      train: true
  test:
    class_path: fl_framework.data.datasets.CIFAR10Dataset
    params:
      data_dir: data_cache        # ← directory only
      train: false
  partition:            # 2 spaces ← MUST line up with “batch_size”
    iid: true # 4 spaces
    seed: 42

model:
  class_path: fl_framework.components.models.resnet_18_for_10.ResNet18For10
  params:
    in_channels: 3
    

training:
  rounds: 10
  round_steps: 3000
  train_loss_function:
      class_path: torch.nn.CrossEntropyLoss
    # params:
    #   label_smoothing: 0.1
  test_loss_function:
    class_path: torch.nn.CrossEntropyLoss
  metrics:
  - class_path: fl_framework.utils.metrics.TopKAccuracy
    params:
      k: 1
optimizer:
  class_path: fl_framework.components.optimizers.sgd.SGD
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5.0e-4
    lr_decay_rate: 0.1
    lr_decay_milestone: [7]
aggregator:
  class_path: fl_framework.components.aggregators.compress.CompressAggregator
  params:
    m: 6
    r: 4
    k: 6
honest:
  num_clients: 16
byzantine:
  num_clients: 0
  attack:
    class_path: fl_framework.components.attacks.random_noise.RandomNoiseAttack
    params: {}
